# Generated by Django 3.0.3 on 2020-05-06 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amoapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paintsleads',
            old_name='lead_id',
            new_name='lead',
        ),
        migrations.RenameField(
            model_name='paintsleads',
            old_name='paint_id',
            new_name='paint',
        ),
    ]
